const actionTypes = {
  LEVEL_UP: "LEVEL_UP",
  POWER_UP: "POWER_UP",
  TOGGLE_MENU: "TOGGLE_MENU",
  STORE_POSTS: "STORE_POSTS",
  EDIT_POSTS: "EDIT_POSTS",
  DELETE_POSTS: "DELETE_POSTS",
  STORE_PROFILE_INFORMATION: "STORE_PROFILE_INFORMATION",
  FETCH_PROFILE_INFORMATION: "FETCH_PROFILE_INFORMATION"
};

export default actionTypes;
